version: '3.8'

services:
  app:
    image: rss-comb:latest
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=rss_user
      - DB_PASSWORD=${DB_PASSWORD:-rss_password}
      - DB_NAME=rss_comb
      - FEEDS_DIR=/app/feeds
      - PORT=${PORT:-8080}
      - WORKER_COUNT=${WORKER_COUNT:-5}
      - SCHEDULER_INTERVAL=${SCHEDULER_INTERVAL:-30}
      - API_ACCESS_KEY=${API_ACCESS_KEY:-}
      - TZ=${TZ:-UTC}
      - GIN_MODE=release
    volumes:
      - ./feeds:/app/feeds:ro
      - app_logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:${PORT:-8080}/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s  # Longer start period for production (DB connection, migrations, etc.)
    networks:
      - rss-comb-network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rss_comb
      - POSTGRES_USER=rss_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-rss_password}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rss_user -d rss_comb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rss-comb-network
    ports:
      - "127.0.0.1:5432:5432" # Only bind to localhost for security


networks:
  rss-comb-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local
  postgres_logs:
    driver: local
